name: Build and Push Docker Images to ECR

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: read
  id-token: write  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

    - name: Build, Tag & Push Docker Image for Node.js API
      run: |
        IMAGE_NAME=nodejs-api
        ECR_REGISTRY=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
        ECR_REPOSITORY=$ECR_REGISTRY/my-demo-repo

        # Build Docker Image
        docker build -t $IMAGE_NAME .

        # Tag Docker Image
        docker tag $IMAGE_NAME:latest $ECR_REPOSITORY:latest

        # Push Docker Image to ECR
        docker push $ECR_REPOSITORY:latest

    - name: Cleanup local Docker images
      run: |
        docker image prune -f
